=== A-Diaz-M/Lenguaje-de-marcas/Validación XML - DTD II/Ej1/factura.dtd
<!-- 
Nombre: Juan Pérez 
Curso: Lenguajes de Marcas 
Fecha: 29/03/2025 
Ejercicio: Factura electrónica – DTD 
-->
<!ELEMENT factura (datos-emisor, datos-cliente, detalle-factura)>
<!ATTLIST factura
    numero CDATA #REQUIRED
    fecha  CDATA #REQUIRED>

<!ELEMENT datos-emisor (nombre, cif, telefono)>
<!ELEMENT datos-cliente (nombre, cif, telefono)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

<!ELEMENT detalle-factura (linea+)>
<!ATTLIST detalle-factura
    importe CDATA #REQUIRED>

<!ELEMENT linea (descripcion, cantidad, pvp, oferta?)>
<!ATTLIST linea
    codigo-articulo ID   #REQUIRED
    tipo           (Libro|DVD|Varios) #REQUIRED>

<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT pvp (#PCDATA)>

<!ELEMENT oferta EMPTY>

=== A-Diaz-M/Lenguaje-de-marcas/Validación XML - DTD II/Ej1/factura.xml
<!-- 
Nombre: Alejandro Díaz 
Curso: 1º DAM
Fecha: 29/03/2025
Ejercicio: Factura electrónica 
-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">
<factura numero="F001" fecha="29/03/2025">
  <!-- Datos del emisor -->
  <datos-emisor>
    <nombre>Librería El Saber</nombre>
    <cif>A12345678</cif>
    <telefono>912345678</telefono>
  </datos-emisor>
  <!-- Datos del cliente -->
  <datos-cliente>
    <nombre>Biblioteca Central</nombre>
    <cif>B87654321</cif>
    <telefono>987654321</telefono>
  </datos-cliente>
  <!-- Detalle de la factura -->
  <detalle-factura importe="150.00">
    <!-- Línea de producto sin oferta -->
    <linea codigo-articulo="A1" tipo="Libro">
      <descripcion>El Quijote</descripcion>
      <cantidad>2</cantidad>
      <pvp>25.00</pvp>
    </linea>
    <!-- Línea de producto con oferta -->
    <linea codigo-articulo="A2" tipo="DVD">
      <descripcion>Documental: Historia del Arte</descripcion>
      <cantidad>1</cantidad>
      <pvp>30.00</pvp>
      <oferta/>
    </linea>
  </detalle-factura>
</factura>
