<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Alejandro Díaz 
Curso: 1º DAM
Fecha: 29/03/2025
Ejercicio: 2-2 - Conversación
-->
<!DOCTYPE conversacion [
  <!ELEMENT conversacion (mensaje+)>
  <!ELEMENT mensaje (de, para, hora, texto)>
  <!ELEMENT de (#PCDATA)>
  <!ELEMENT para (#PCDATA)>
  <!ELEMENT hora (#PCDATA)>
  <!ELEMENT texto (#PCDATA | b)*>
  <!ELEMENT b (#PCDATA)>
]>
<conversacion>
  <mensaje>
    <de>Ana</de>
    <para>Luis</para>
    <hora>10:00</hora>
    <texto>Aprendiendo <b>XML</b></texto>
  </mensaje>
</conversacion>
